---
title: "Technical Report"
author: "Kanyin Olagbegi and Will Lonnquist"
date: "12/8/2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(readr)
library(dplyr)

data <- read_delim('revent.TXT', delim = ";")

dataFinal <- data %>%
  
  # Filtering for PGA TOUR Stroke Play Events
  filter(`Official Event(Y/N)` == "Y") %>%
  
  # Changing variables to the proper types
  mutate(`Total Rounds` = as.numeric(`Total Rounds)`),
         `Finish Position(numeric)` = as.numeric(`Finish Position(numeric)`),
         `Birdies` = as.numeric(`Birdies`),
         `Total Holes Over Par` = as.numeric(`Total Holes Over Par`),
         `Drives Over 300 Yards (# of Drives)` = as.numeric(`Drives Over 300 Yards (# of Drives)`),
         `3-Putt Avoid(Total 3 Putts)` = as.numeric(`3-Putt Avoid(Total 3 Putts)`),
         `Avg Distance of Putts Made(Total Distance of Putts)` = as.numeric(`Avg Distance of Putts Made(Total Distance of Putts)`),
         `Total Holes Played` = as.numeric(`Total Holes Played`),
         `Total Greens in Regulation` = as.numeric(`Total Greens in Regulation`),
         `App. 50-125 Yards(ft)` = as.numeric(`App. 50-125 Yards(ft)`),
         `App.  50-125 Yards(attempts)` = as.numeric(`App.  50-125 Yards(attempts)`),
         
         #Creating our desired variables
         cutMade = as.factor(ifelse(`Finish Position(numeric)` < 999, 1, 0)),
         birdiesPerRound = `Birdies` / `Total Rounds`,
         GIRsPerRound = `Total Greens in Regulation` / `Total Rounds`,
         # GIRsPerRound = `Total Greens in Regulation` / `Total Holes Played`,
         overParHolesPerRound = `Total Holes Over Par` / `Total Rounds`,
         ThreePuttsPerRound = `3-Putt Avoid(Total 3 Putts)` / `Total Rounds`,
         over300DrivesPerRound = `Drives Over 300 Yards (# of Drives)` /
           `Total Rounds`,
         distPuttsMadePerRound = `Avg Distance of Putts Made(Total Distance of Putts)` / `Total Rounds`,
         proxToHoleApproach = `App. 50-125 Yards(ft)` / `App.  50-125 Yards(attempts)`)  %>%

  #Selecting our desired columns
  select(`Player Name`,
        `Event Name`,
        cutMade,
        birdiesPerRound,
        GIRsPerRound,
        overParHolesPerRound,
        ThreePuttsPerRound,
        over300DrivesPerRound,
        distPuttsMadePerRound,
        proxToHoleApproach)

# Removing observations with missing values 
# Source for code: https://stackoverflow.com/questions/4862178/remove-rows-with-all-or-some-nas-missing-values-in-data-frame 
dataFinal <- dataFinal[complete.cases(dataFinal), ]

head(dataFinal)
# nrow(dataFinal)
```

```{r}
# Exploratory Data Analyis
library(ggplot2)

ggplot(dataFinal, aes(x=cutMade, y=GIRsPerRound)) + 
  geom_boxplot() +
  ggtitle("Greens in Regulation Per Round For Cut/Non-Cut Players")

ggplot(dataFinal, aes(x=cutMade, y=proxToHoleApproach)) + 
  geom_boxplot() +
  ggtitle("Approach Shot Proximity Per Round For Cut/Non-Cut Players")
```

```{r warning=FALSE, message=FALSE}
# Splitting data into train and test subsets

# split 80/20 --------------------------
set.seed(123)
n <- nrow(dataFinal)
train_id <- sample(1:n, size=round(n*0.8)) # select approx 80% of the row numbers between 1 and n
train1 <- dataFinal[train_id,] # the data set we'll train the model on
test1 <- dataFinal[-train_id,] # the data set we'll test the model on
```

```{r warning=FALSE, message=FALSE}
# Building Random Forest
library(randomForest)
library(pROC)

# Setting formula for random forest
f2 <- as.formula(cutMade ~ GIRsPerRound + ThreePuttsPerRound + over300DrivesPerRound + distPuttsMadePerRound + proxToHoleApproach)

# Training forest
set.seed(500)
mod_forest2 <- randomForest(f2, data = train1, ntree = 300, mtry = 2)
mod_forest2

sum(diag(mod_forest2$confusion)) / nrow(train1)

# predict on test and evaluate the model on test using auc-----------------------
pred_AUC2 <- predict(mod_forest2, test1, type = "prob")[,1]

test1 <- test1 %>% mutate(prediction2 = pred_AUC2)

roc_obj <- roc(test1$cutMade, test1$prediction2)
auc(roc_obj)
plot(roc_obj)
```

```{r message=FALSE, warning=FALSE}
# Variable Importance

# Get variable importance, code from textbook
library(tibble)
importance(mod_forest2) %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  arrange(desc(MeanDecreaseGini))

# Create Variable Importance Plot
varImpPlot(mod_forest2, main = "Variable Importance")
```